/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphics;

import Database.DB_OracleConnection;
import javax.swing.JOptionPane;

/**
 *
 * @author Leonardo
 */
public class GUI_Report extends javax.swing.JFrame {
    private DB_OracleConnection db;
    /**
     * Creates new form GUI_Report
     */
    public GUI_Report() {
        initComponents();
    }
    
    public void setConnection(DB_OracleConnection connection) {
        db = connection;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txtModalidade = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMedico = new javax.swing.JTextField();
        txtTreinador = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnRelatorio1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNroAtletas = new javax.swing.JTextField();
        txtNacao = new javax.swing.JTextField();
        btnRelatorio2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnRelatorio4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtModalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModalidadeActionPerformed(evt);
            }
        });

        jLabel1.setText("Modalidade:");

        jLabel2.setText("Médico:");

        txtMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedicoActionPerformed(evt);
            }
        });

        txtTreinador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTreinadorActionPerformed(evt);
            }
        });

        jLabel3.setText("Treinador:");

        btnRelatorio1.setText("Gerar Relatório");
        btnRelatorio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorio1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtModalidade)
                    .addComponent(txtMedico)
                    .addComponent(txtTreinador, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addComponent(btnRelatorio1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtModalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTreinador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRelatorio1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tipo 1", jPanel1);

        jLabel4.setText("Nro Atletas:");

        jLabel5.setText("Nação:");

        txtNroAtletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNroAtletasActionPerformed(evt);
            }
        });

        txtNacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNacaoActionPerformed(evt);
            }
        });

        btnRelatorio2.setText("Gerar Relatório");
        btnRelatorio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorio2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRelatorio2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNacao, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(txtNroAtletas))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNroAtletas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRelatorio2)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tipo 2", jPanel2);

        btnRelatorio4.setText("Gerar Relatório");
        btnRelatorio4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorio4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRelatorio4)
                .addContainerGap(141, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRelatorio4)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tipo 4", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtModalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModalidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModalidadeActionPerformed

    private void txtMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicoActionPerformed

    private void txtTreinadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTreinadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTreinadorActionPerformed

    private void txtNacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNacaoActionPerformed

    private void txtNroAtletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNroAtletasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNroAtletasActionPerformed

    private void btnRelatorio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorio1ActionPerformed
        // TODO add your handling code here:
        String modalidade = txtModalidade.getText();
        String medico = txtMedico.getText();
        String treinador = txtTreinador.getText();
        
        System.out.println(modalidade);
        System.out.println(medico);
        System.out.println(treinador);
        
        if ("".equals(medico) || "".equals(modalidade) || "".equals(treinador)) {
            JOptionPane.showMessageDialog(this, "Medico, modalidade ou treinador não preenchidos.", "Falta preencher...", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        GUI_ReportTable rt = new GUI_ReportTable();
        rt.setConnection(db);
        rt.setDescription("Atletas de " + modalidade + ", atendidos por " + medico + ", treinados por " + treinador + ".");
        
        
        if (rt.loadReport1(modalidade, medico, treinador))
            rt.setVisible(true);
    }//GEN-LAST:event_btnRelatorio1ActionPerformed

    private void btnRelatorio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorio2ActionPerformed
        // TODO add your handling code here:
        String nAtletas = txtNroAtletas.getText();
        String nacao = txtNacao.getText();
        
        if (nAtletas.equals("") || nacao.equals("")) {
            JOptionPane.showMessageDialog(this, "Número de atletas ou nação não preenchidos.", "Falta preencher...", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int num = 0;
        try {
            num = Integer.parseInt(nAtletas);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Número inválido para 'Nro Atletas'.", "Entrada inválida...", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        GUI_ReportTable rt = new GUI_ReportTable();
        rt.setConnection(db);
        rt.setDescription("Médicos que atenderam ao menos " + nAtletas + " atletas da nação " + nacao + ".");
        rt.loadReport2(num, nacao);
        rt.setVisible(true);
    }//GEN-LAST:event_btnRelatorio2ActionPerformed

    private void btnRelatorio4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorio4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRelatorio4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRelatorio1;
    private javax.swing.JButton btnRelatorio2;
    private javax.swing.JButton btnRelatorio4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtMedico;
    private javax.swing.JTextField txtModalidade;
    private javax.swing.JTextField txtNacao;
    private javax.swing.JTextField txtNroAtletas;
    private javax.swing.JTextField txtTreinador;
    // End of variables declaration//GEN-END:variables
}
