CREATE TABLE MODALIDADE(
	CODIGO INTEGER NOT NULL,
	NOME VARCHAR2(20) UNIQUE NOT NULL,
	DESCRICAO VARCHAR2(500) NOT NULL,
	CONSTRAINT pk_modalidade primary key(CODIGO)
);

CREATE TABLE NACAO(
	NOME VARCHAR2(30) NOT NULL,
	CONTINENTE VARCHAR2(9) NOT NULL,
	NUMERO_ATLETAS INTEGER NOT NULL,
	IMAGEM_BANDEIRA VARCHAR2(30) NOT NULL,
	HINO_NACIONAL VARCHAR2(500) NOT NULL,
	MODALIDADE_PRINCIPAL INTEGER NOT NULL,
	CONSTRAINT fk_modalidade_nacao
		FOREIGN KEY(MODALIDADE_PRINCIPAL) REFERENCES MODALIDADE
		ON DELETE CASCADE,
	CONSTRAINT pk_nacao PRIMARY KEY (NOME) 
);

CREATE TABLE ATLETA(
    NUMERO_PASSAPORTE VARCHAR2(20) NOT NULL,
    NOME VARCHAR2(50) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    ALTURA DECIMAL(4,1),
    PESO DECIMAL(4,1),
    SEXO CHAR(1) NOT NULL,
    NACAO VARCHAR2(30) NOT NULL,
	CONSTRAINT fk_nacao_atleta
		FOREIGN KEY(NACAO) REFERENCES NACAO
		ON DELETE CASCADE,
	CONSTRAINT ck_sexo check(sexo in ('M','F')),
    CONSTRAINT ck_altura check(altura between 100 and 260),
    CONSTRAINT ck_peso check(peso between 20 and 300),
    CONSTRAINT pk_atleta PRIMARY KEY(NUMERO_PASSAPORTE)
);

CREATE TABLE DISPUTA(
	ATLETA VARCHAR2(20) NOT NULL,
	MODALIDADE INTEGER NOT NULL,
	CONSTRAINT pk_disputa PRIMARY KEY(ATLETA,MODALIDADE),
	CONSTRAINT fk_numeroPassaporte_disputa
		FOREIGN KEY (ATLETA) REFERENCES ATLETA
		ON DELETE CASCADE,
	CONSTRAINT fk_modalidade_disputa
		FOREIGN KEY(MODALIDADE) REFERENCES MODALIDADE
		ON DELETE CASCADE
);

CREATE TABLE ESPORTISTA(
	ATLETA VARCHAR2(20) NOT NULL,
	MODALIDADE INTEGER NOT NULL,
	SITUACAO VARCHAR2(12) NOT NULL,
	CONSTRAINT ck_situacao CHECK(SITUACAO IN ('Irregular','Regular','Recuperacao','banido')),
	CONSTRAINT pk_esportista PRIMARY KEY(ATLETA,MODALIDADE),
	CONSTRAINT fk_modalidade_atleta
		FOREIGN KEY(ATLETA,MODALIDADE) REFERENCES DISPUTA
		ON DELETE CASCADE
);


CREATE TABLE PREPARADOR(
	CODIGO INTEGER NOT NULL,
	NOME VARCHAR2(50) NOT NULL,
	CIDADE VARCHAR2(30) NOT NULL,
	ESTADO VARCHAR2(30) NOT NULL,
	PAIS VARCHAR2(30) NOT NULL,
	SEXO CHAR(1) NOT NULL,
	DIA_NASCIMENTO SMALLINT NOT NULL,
	MES_NASCIMENTO SMALLINT NOT NULL,
	ANO_NASCIMENTO SMALLINT NOT NULL,
	EMAIL VARCHAR2(30) NOT NULL,
	SENHA INTEGER NOT NULL,
	CPF VARCHAR2(14),
	NUMERO_PASSAPORTE VARCHAR2(20),
	CONSTRAINT pk_codigo PRIMARY KEY(CODIGO),
	CONSTRAINT pk_cpf UNIQUE(CPF),
	CONSTRAINT pk_passaporte UNIQUE(NUMERO_PASSAPORTE)
);


CREATE TABLE TELEFONE_PREPARADOR(
	PREPARADOR INTEGER NOT NULL,
	ID_REGIAO DECIMAL(2,0) NOT NULL,
	NUMERO INTEGER NOT NULL,
	CONSTRAINT pk_telefonePreparador PRIMARY KEY(PREPARADOR,ID_REGIAO,NUMERO),
	CONSTRAINT fk_telefonePreparador
		FOREIGN KEY(PREPARADOR) REFERENCES PREPARADOR
		ON DELETE CASCADE
);

CREATE TABLE ATIVIDADE_RECUPERACAO(
	ID INTEGER NOT NULL,
	DESCRICAO VARCHAR2(500) NOT NULL,
	CONSTRAINT pk_atividadeRecuperacao PRIMARY KEY(ID)
);

CREATE TABLE MODO_PREPARO(
	ID INTEGER NOT NULL,
	DESCRICAO VARCHAR2(500)NOT NULL,
	CONSTRAINT pk_modoPreparo PRIMARY KEY(ID)
);

CREATE TABLE TREINO(
	ID INTEGER NOT NULL,
	DESCRICAO VARCHAR2(500) NOT NULL,
	MODO_PREPARO INTEGER NOT NULL,
	ATIVIDADE_RECUPERACAO INTEGER NOT NULL,
	CONSTRAINT pk_treino PRIMARY KEY(ID),
	CONSTRAINT fk_modoPreparo
		FOREIGN KEY(MODO_PREPARO) REFERENCES MODO_PREPARO
		ON DELETE CASCADE,
	CONSTRAINT fk_atividadeRecuperacao
		FOREIGN KEY(ATIVIDADE_RECUPERACAO) REFERENCES ATIVIDADE_RECUPERACAO
		ON DELETE CASCADE
);

CREATE TABLE ROTINA_TREINO(
	ATLETA VARCHAR2(20) NOT NULL,
	MODALIDADE INTEGER NOT NULL,
	DIA_DA_SEMANA VARCHAR2(7) NOT NULL,
	PREPARADOR INTEGER NOT NULL,
	TEMPO VARCHAR2(5) NOT NULL,
	TREINO INTEGER NOT NULL,
	CONSTRAINT pk_rotinaTreino PRIMARY KEY(ATLETA,MODALIDADE,DIA_DA_SEMANA),
	CONSTRAINT fk_rotinaTreino_preparador
		FOREIGN KEY(PREPARADOR) REFERENCES PREPARADOR
		ON DELETE CASCADE,
	CONSTRAINT fk_rotinaTreino_treino
		FOREIGN KEY(TREINO) REFERENCES TREINO
		ON DELETE CASCADE,
	CONSTRAINT fk_atleta_modalidade
		FOREIGN KEY (ATLETA,MODALIDADE) REFERENCES ESPORTISTA
		ON DELETE CASCADE,
	CONSTRAINT ck_diaDaSemana check( DIA_DA_SEMANA IN('SEGUNDA','TERCA','QUARTA','QUINTA','SEXTA','SABADO','DOMINGO'))
);

CREATE TABLE MEDICO(
	ID INTEGER NOT NULL,
	NOME VARCHAR2(50) NOT NULL,
	CRM INTEGER NOT NULL,
	DOCUMENTO_IDENTIDADE VARCHAR2(20) NOT NULL,
	CONSTRAINT pk_medico PRIMARY KEY(ID)
);

CREATE TABLE ENDERECO_MEDICO(
	MEDICO INTEGER NOT NULL,
	LOGRADOURO VARCHAR2(30) NOT NULL,
	COMPLEMENTO VARCHAR2(30),
	NUMERO SMALLINT,
	CONSTRAINT pk_enderecoMedico PRIMARY KEY(MEDICO),
	CONSTRAINT fk_enderecoMedico_medico
		FOREIGN KEY(MEDICO) REFERENCES MEDICO
		ON DELETE CASCADE
);



CREATE TABLE TELEFONE_MEDICO(
	MEDICO INTEGER NOT NULL,
	ID_REGIAO SMALLINT NOT NULL,
	NUMERO INTEGER NOT NULL,
	CONSTRAINT pk_telefoneMedico PRIMARY KEY(MEDICO,ID_REGIAO,NUMERO),
	CONSTRAINT fk_telefoneMedico_medico
		FOREIGN KEY(MEDICO) REFERENCES MEDICO
		ON DELETE CASCADE
);


CREATE TABLE LESAO(
	ID INTEGER NOT NULL,
	DESCRICAO VARCHAR2(500) NOT NULL,
	CONSTRAINT pk_lesao PRIMARY KEY(ID)
);

CREATE TABLE TESTE_DOPING(
		ID INTEGER NOT NULL,
		DESCRICAO VARCHAR2(500) NOT NULL,
		DIA SMALLINT NOT NULL,
		MES SMALLINT NOT NULL,
		ANO SMALLINT NOT NULL,
		RESULTADO VARCHAR(8),
		CONSTRAINT pk_testeDoping PRIMARY KEY(ID),
		CONSTRAINT ck_diaDoping CHECK(DIA >=0  AND DIA <= 31),
		CONSTRAINT ck_mesDoping CHECK(MES >=0  AND MES <= 12),
		CONSTRAINT ck_anoDoping CHECK(ANO >=1900 AND ANO <= 3000)
);

CREATE TABLE REALIZA(
	ATLETA VARCHAR2(20) NOT NULL,
	MODALIDADE INTEGER NOT NULL,
	TESTE_DOPING INTEGER NOT NULL,
	MEDICO INTEGER NOT NULL,
	CONSTRAINT pk_realiza PRIMARY KEY(ATLETA,MODALIDADE,TESTE_DOPING),
	CONSTRAINT fk_atleta_modalidade_realiza
		FOREIGN KEY(ATLETA,MODALIDADE) REFERENCES ESPORTISTA
		ON DELETE CASCADE,
	CONSTRAINT fk_testeDoping_realiza
		FOREIGN KEY(TESTE_DOPING) REFERENCES TESTE_DOPING
		ON DELETE CASCADE,
	CONSTRAINT fk_medico_realiza
		FOREIGN KEY(MEDICO) REFERENCES MEDICO
		ON DELETE CASCADE
);

CREATE TABLE CONSULTA(
	ATLETA VARCHAR2(20) NOT NULL,
	MEDICO INTEGER NOT NULL,
	CONSTRAINT pk_consulta PRIMARY KEY(ATLETA,MEDICO),
	CONSTRAINT fk_atleta
		FOREIGN KEY(ATLETA) REFERENCES ATLETA
		ON DELETE CASCADE,
	CONSTRAINT fk_medico
		FOREIGN KEY(MEDICO) REFERENCES MEDICO
		ON DELETE CASCADE
);

CREATE TABLE DIAGNOSTICO(
	ID INTEGER NOT NULL,
	DESCRICAO VARCHAR2(500) NOT NULL,
	CONSTRAINT pk_diagnostico PRIMARY KEY(ID)
);


CREATE TABLE ATENDIMENTO(
	ID INTEGER NOT NULL,
	ATLETA VARCHAR2(20) NOT NULL,
	MEDICO INTEGER NOT NULL,
	DIAGNOSTICO INTEGER NOT NULL,
	DIA SMALLINT NOT NULL,
	MES SMALLINT NOT NULL,
	ANO SMALLINT NOT NULL,
	CONSTRAINT pk_atendimento PRIMARY KEY(ID),
	CONSTRAINT ck_diaAtendimento CHECK(DIA >=0  AND DIA <= 31),
	CONSTRAINT ck_mesAtendimento CHECK(MES >=0  AND MES <= 12),
	CONSTRAINT ck_anoAtendimento CHECK(ANO >=1900 AND ANO <= 3000),
	CONSTRAINT uq_atendimento UNIQUE(ATLETA,MEDICO,DIA,MES,ANO),
	CONSTRAINT fk_atleta_medico
		FOREIGN KEY(ATLETA,MEDICO) REFERENCES CONSULTA
		ON DELETE CASCADE,
	CONSTRAINT fk_diagnostico
		FOREIGN KEY(DIAGNOSTICO) REFERENCES DIAGNOSTICO
		ON DELETE CASCADE
);

CREATE TABLE SINTOMA(
	ID INTEGER NOT NULL,
	DESCRICAO VARCHAR2(500) NOT NULL,
	CONSTRAINT pk_sintoma PRIMARY KEY(ID)
);
CREATE TABLE SINTOMAS_PACIENTES(
	SINTOMA INTEGER NOT NULL,
	ATENDIMENTO INTEGER NOT NULL,
	CONSTRAINT pk_sintomasPacientes PRIMARY KEY(ATENDIMENTO,SINTOMA),
	CONSTRAINT fk_sintoma
		FOREIGN KEY(SINTOMA) REFERENCES SINTOMA
		ON DELETE CASCADE,
	CONSTRAINT fk_atendimento 
		FOREIGN KEY(ATENDIMENTO) REFERENCES ATENDIMENTO
		ON DELETE CASCADE
);
	
CREATE TABLE METODO_TRATAMENTO(
	ID INTEGER NOT NULL,	
	DESCRICAO_METODO VARCHAR2(500) NOT NULL,
	DESCRICAO_EFETIVIDADE VARCHAR2(500) NOT NULL,
	CURA SMALLINT  NOT NULL,
	RECUPERACAO SMALLINT NOT NULL,
	CONSTRAINT pk_metodoTratamento PRIMARY KEY(ID),
  CONSTRAINT ck_cura CHECK(CURA IN (1,0)),
  CONSTRAINT ck_recuperacao CHECK(RECUPERACAO IN (1,0))
);

CREATE TABLE DIAGNOSTICO_METODO(
	DIAGNOSTICO INTEGER NOT NULL,
	METODO INTEGER NOT NULL,	
	CONSTRAINT pk_diagnosticoMetodo PRIMARY KEY(DIAGNOSTICO,METODO),
	CONSTRAINT fk_diagnostico_metodo
		FOREIGN KEY(DIAGNOSTICO) REFERENCES DIAGNOSTICO
		ON DELETE CASCADE,
	CONSTRAINT fk_metodo
		FOREIGN KEY(METODO) REFERENCES METODO_TRATAMENTO
		ON DELETE CASCADE
);

CREATE TABLE TRATAMENTO(
	ATLETA VARCHAR2(20) NOT NULL,
	MODALIDADE INTEGER NOT NULL,
	MEDICO INTEGER NOT NULL,
	LESAO INTEGER NOT NULL,
	CONSTRAINT pk_tratamento PRIMARY KEY(ATLETA,MODALIDADE,MEDICO,LESAO),
	CONSTRAINT fk_atletaModalidadeTratamento
		FOREIGN KEY(ATLETA,MODALIDADE) REFERENCES ESPORTISTA
		ON DELETE CASCADE,
	CONSTRAINT fk_medicoTratamento
		FOREIGN KEY(MEDICO) REFERENCES MEDICO
		ON DELETE CASCADE,
	CONSTRAINT fk_lesaoTratamento
		FOREIGN KEY(LESAO) REFERENCES LESAO
		ON DELETE CASCADE
);